const server = require("./server")
const axios = require("axios")
const fs = require("fs");

const endpoint = "http://localhost:3000"

afterAll( () => server.close())


describe("send pages", () => {

    test("send main.html", () => axios.get(`${endpoint}/main`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("main.html", "utf8")) )
    )
    test("send add_book.html", () => axios.get(`${endpoint}/add_book`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("add_book.html", "utf8")) )
    )
    test("send add_reader.html", () => axios.get(`${endpoint}/add_reader`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("add_reader.html", "utf8")) )
    )
    test("send del_book.html", () => axios.get(`${endpoint}/del_book`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("del_book.html", "utf8")) )
    )
    test("send del_reader.html", () => axios.get(`${endpoint}/del_reader`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("del_reader.html", "utf8")) )
    )
    test("send give_book.html", () => axios.get(`${endpoint}/give_book`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("give_book.html", "utf8")) )
    )
    test("send back_book.html", () => axios.get(`${endpoint}/back_book`)
        .then( resp => expect(resp.data).toBe(fs.readFileSync("back_book.html", "utf8")) )
    )

    test("send main.html", () => axios.get(`${endpoint}/main`)
        .then( resp => expect(resp.status).toBe(200) )
    )
    test("send add_book.html", () => axios.get(`${endpoint}/add_book`)
        .then( resp => expect(resp.status).toBe(200) )
    )
    test("send add_reader.html", () => axios.get(`${endpoint}/add_reader`)
        .then( resp => expect(resp.status).toBe(200) )
    )
    test("send del_book.html", () => axios.get(`${endpoint}/del_book`)
        .then( resp => expect(resp.status).toBe(200) )
    )
    test("send del_reader.html", () => axios.get(`${endpoint}/del_reader`)
        .then( resp => expect(resp.status).toBe(200) )
    )
    test("send give_book.html", () => axios.get(`${endpoint}/give_book`)
        .then( resp => expect(resp.status).toBe(200) )
    )
    test("send back_book.html", () => axios.get(`${endpoint}/back_book`)
        .then( resp => expect(resp.status).toBe(200) )
    )
})